elf2flt: fix unused warning for e1/bfin targets
The one call site for this func is inside of an e1/bfin ifdef check,
so add the same logic to the definition to fix a build error:
elf2flt.c:212:1: error: ‘get_symbol_offset’ defined but not used [-Werror=unused-function]

Signed-off-by: Mike Frysinger <vapier@gentoo.org>